### ISSUE TITLE
Unnecessary mutex in awsauth.go?

### ISSUE THREAD

**Issue by justonia** [smartystreets/go-aws-auth#22]
I am not sure why the "signMutex" is necessary for concurrent access to the signing version map. In go maps are safe for concurrent access for any number of readers, it's only when something else may be writing to the map that you would need to protect it:

https://groups.google.com/forum/#!msg/golang-nuts/HpLWnGTp-n8/hyUYmnWJqiQJ

Unless I am missing something, the global map is never written to.

**Comment by mdwhatcott** [comment]
According to my reading of the code, the mutex was protecting a package-level (exported) `Keys` variable, which has since been removed. Let me know if I've unknowingly done something rash...
